name: flutter_test_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.3.8
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"

  flutter_lints: ^2.0.0


flutter_launcher_icons:
 windows:
    generate: false
    image_path: "assets/images/icon.ico"


flutter:
  assets:
    - assets/images/
  uses-material-design: true


