name: eta_regulator_board_admin_toolbox
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  window_manager: ^0.3.8
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  mask_text_input_formatter: ^2.8.0
  qr_flutter: ^4.1.0
  file_picker: ^6.1.1
  path_provider: ^2.1.2
  flutter_native_splash: ^2.3.10
  uuid: ^4.3.3
  dio: ^5.4.0
  device_info_plus: ^9.1.2
  fluttertoast: ^8.2.4
  get_it: ^7.6.7
  socket_io_client: ^2.0.3+1
  archive: ^3.4.10
  path: ^1.9.0
  collection: ^1.18.0
  http_parser: ^4.0.2
  html: ^0.15.4
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  flutter_form_builder: ^9.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter_native_splash:
  web: false
  android_12:
    image: "assets/images/favicon.png"
    icon_background_color: "#ffffff"


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/favicon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  windows:
    generate: true
    image_path: "assets/images/icon.ico"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
    - assets/deployment/
    - assets/deployment/configs/
    - assets/deployment/distro/

